# SensibleMetrics WebDocs Document Generator Template configuration
---
webdocs:
  storage:
    base-path: ${DOC_STORAGE_PATH:${TEMP}}
  template:
    name-pattern: ${DOC_TEMPLATE_NAME:templates/invoice.docx}
    format:
      marker-mappings:
        id:
          name: "id"
          pattern: "# %s"
        company:
          name: "company"
        partner:
          name: "partner"
        product:
          name: "product"
        amount:
          name: "amount"
        price:
          name: "price"
        data:
          name: "data"
        date:
          name: "date"
          pattern: "yyyy-MM-dd HH:mm:ss"
        total:
          name: "total"
