global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s

scrape_configs:
  - job_name: spring-actuator
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /management/actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['localhost:8088']
