# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
version-template: 'v$MAJOR.$MINOR.$PATCH'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ":boom: Breaking changes"
    labels:
      - breaking
  - title: 🚨 Removed
    label: removed
  - title: ":tada: Major features and improvements"
    labels:
      - major-enhancement
      - major-rfe
  - title: 🐛 Major bug fixes
    labels:
      - major-bug
  - title: ⚠️ Deprecated
    label: deprecated
  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
      - rfe
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: ":construction_worker: Changes for plugin developers"
    labels:
      - developer
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    label: dependencies
  - title: 📝 Documentation updates
    label: documentation
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: '🚀 New Features'
    labels:
      - 'type:features'
  - title: '🐞 Bugs Fixes'
    labels:
      - 'type:fix'
  - title: '📚 Documentation'
    labels:
      - 'type:documentation'
  - title: '🛠 Configuration'
    labels:
      - 'type:config'

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  <!-- Optional: add a release summary here -->
  $CHANGES
