apiVersion: batch/v1
kind: Job
metadata:
  name: documents-db-schema-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
        - name: flyway
          image: boxfuse/flyway:5
          args: ["migrate"]
          env:
            - name: FLYWAY_URL
              value: "jdbc:p6spy:postgresql://localhost:5432/documentdb"

            - name: FLYWAY_USER
              valueFrom:
                configMapKeyRef:
                  name: documents-db-config
                  key: POSTGRES_USER
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documents-db-secrets
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: sql-config
              mountPath: /flyway/sql
      volumes:
        - name: sql-config
          configMap:
            name: documents-db-sql

      restartPolicy: Never
