github:
  description: "SensibleMetrics Component-based WebDocs Java Framework"
  homepage: https://github.com/AlexRogalskiy/ws-documents/
  labels:
    - java
    - spring-bootstrap
    - build-management
  features:
    # Enable wiki for documentation
    wiki: true
    # Enable issue management
    issues: true
    # Enable projects for project management boards
    projects: true
  enabled_merge_buttons:
    # enable squash button:
    squash:  true
    # enable merge button:
    merge:   true
    # disable rebase button:
    rebase:  false
  ghp_branch:  master
  ghp_path:    /docs

jekyll:
  whoami: master
  target: asf-staging-jekyll       # output branches need to be asf-site OR asf-staging*
#  outputdir: outputdir            # MAY be needed, but generally can be left out

publish:
  whoami: asf-staging-jekyll

notifications:
  commits:              commits@foo.apache.org
  # Send all issue emails (new, closed, comments) to issues@
  issues:               issues@foo.apache.org
  # Send new/closed PR notifications to dev@
  pullrequests_status:  dev@foo.apache.org
  # Send individual PR comments/reviews to issues@
  pullrequests_comment: issues@foo.apache.org
