codecov:
  notify:
    require_ci_to_pass: yes
  strict_yaml_branch: master
  branch: master

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches: []

ignore: []
