base_path: "./"
preserve_hierarchy: true

files:
  -
    source: '/docs/**/*.md'
    translation: '/docs/translated_docs/%locale%/**/%original_file_name%'
    languages_mapping: &anchor
      locale:
        'en': 'en'
        'fr': 'fr'
        'ru': 'ru'

  - source: /modules/**/src/main/resources/ValidationMessages.properties
    translation: /modules/**/src/main/resources/%file_name%_%language%.properties
    languages_mapping: *anchor
