kind: ConfigMap
apiVersion: v1
metadata:
  name:  {{ template "documents.name" . }}
  namespace: {{.Release.Namespace}}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  documents-db-user: {{ .Values.db.user }}