kind: ConfigMap
apiVersion: v1
metadata:
  name: documents-db-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernets.io/name: documents-db-config
data:
  POSTGRES_DB: documentdb
  POSTGRES_USER: {{ .Values.db.user }}