# SensibleMetrics WebDocs Web Service Eureka Server configuration
---
server:
  port: 8080
  ssl:
    key-store: modules/eureka/src/main/resources/key-store.jks
    key-store-password: ENC(pZulM4Rk5Tu1gnpQ5WzifnV4EFPN5RBhFNeImxlij/y2Zxa/Iqlp2S8QpcsqKPBM)
    key-password: ENC(q9chaN0OEEaaUJq3FyS65PZDsSf+PUyP+ssgJzkQa23Ft+KeQ6t3YyKf5IWUVfRE)
    key-store-type: PKCS12
    key-alias: spring-boot-ssl-sample
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy: FRAMEWORK
  error:
    path: /error
    include-stacktrace: NEVER
    whitelabel:
      enabled: false
  tomcat:
    mbeanregistry:
      enabled: true
    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s (%D ms)'

spring:
  profiles:
    include: insecure
  output:
    ansi:
      enabled: NEVER
  main:
    log-startup-info: true
  application:
    name: "WebDocs-Eureka-Server-WebService"
  messages:
    basename: i18n/common_messages, i18n/messages
    # 1 hour
    cache-duration: 3600
  aop:
    proxy-target-class: true
  devtools:
    add-properties: false
  mvc:
    throw-exception-if-no-handler-found: true
    log-resolved-exception: true
    locale-resolver: FIXED
    async:
      # 1 hour
      request-timeout: 3600000
  resources:
    add-mappings: true
    chain:
      strategy:
        content:
          enabled: true

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    servlet:
      context-path: /management
    port: 8088
  info:
    build:
      enabled: false
    git:
      mode: FULL
  endpoint:
    jolokia:
      config:
        debug: true
    beans:
      cache:
        time-to-live: 30s
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS
      show-components: ALWAYS
      cache:
        time-to-live: 30s
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ "jolokia", "health", "info", "metrics", "prometheus", "bindings", "beans", "env", "loggers", "streamsbindings", "threaddump", "httptrace", "mappings" ]
      base-path: /actuator
      path-mapping:
        info: status
  metrics:
    tags:
      region: ${spring.application.region:us-east-1}
      type: webdocs
    export:
      prometheus:
        enabled: true
        step: 3m
        pushgateway:
          enabled: false
      jmx:
        enabled: false
      simple:
        enabled: true
        mode: STEP
    enable:
      jvm: false
    web:
      server:
        request:
          autotime:
            enabled: true
      client:
        max-uri-tags: 5
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      slo:
        http:
          server:
            requests: 20ms,50ms

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
---
spring:
  profiles: insecure

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: management/actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: https://localhost:8761/eureka/
---
spring:
  profiles: secure
  security:
    user:
      name: ${EUREKA_USER:user}
      password: ${EUREKA_PASSWORD:password}

# by default every Eureka Server is also an Eureka Client and requires (at least one) service URL to locate a peer.
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: management/actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
