# SensibleMetrics Document Uploader Server configuration
---
server:
  port: 8089
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024

spring:
  application:
    name: "Document-Uploader-Server"
  output:
    ansi:
      enabled: NEVER
  messages:
    basename: i18n/messages
    # 1 hour
    cache-duration: 3600
  aop:
    proxy-target-class: true
  devtools:
    add-properties: false
  main:
    web-application-type: none
  task:
    execution:
      thread-name-prefix: distributor
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100000
  liquibase:
    enabled: false
    drop-first: false
