/**
 * EXCEPT WHERE OTHERWISE STATED, THE INFORMATION AND SOURCE CODE CONTAINED
 * HEREIN AND IN RELATED FILES IS THE EXCLUSIVE PROPERTY OF PARAGON SOFTWARE
 * GROUP COMPANY AND MAY NOT BE EXAMINED, DISTRIBUTED, DISCLOSED, OR REPRODUCED
 * IN WHOLE OR IN PART WITHOUT EXPLICIT WRITTEN AUTHORIZATION FROM THE COMPANY.
 * <p>
 * Copyright (c) 1994-2019 Paragon Software Group, All rights reserved.
 * </p>
 * UNLESS OTHERWISE AGREED IN A WRITING SIGNED BY THE PARTIES, THIS SOFTWARE IS
 * PROVIDED "AS-IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE, ALL OF WHICH ARE HEREBY DISCLAIMED. IN NO EVENT SHALL THE
 * AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF NOT ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.sensiblemetrics.api.ws.commons.common.flow;

import lombok.experimental.UtilityClass;

/**
 * Custom Test Tag utility
 */
@UtilityClass
public final class TestTag {
    public static final String DEFAULT = "DEFAULT";
    public static final String CONFIGURATION = "CONFIGURATION";
    public static final String PROPERTY = "PROPERTY";
    public static final String MODEL = "MODEL";
    public static final String CONTROLLER = "CONTROLLER";
    public static final String SERVICE = "SERVICE";
    public static final String REPOSITORY = "REPOSITORY";
    public static final String CONVERTER = "CONVERTER";
    public static final String SERIALIZER = "SERIALIZER";
    public static final String EXCEPTION = "EXCEPTION";
    public static final String ENUMERATION = "ENUMERATION";
    public static final String FORMATTER = "FORMATTER";
    public static final String FILTER = "FILTER";
    public static final String HANDLER = "HANDLER";
    public static final String UTILITY = "UTILITY";
    public static final String ANNOTATION = "ANNOTATION";
    public static final String FUNCTION = "FUNCTION";
    public static final String CONSTRAINT = "CONSTRAINT";
}
