version: 2

update_configs:
  - package_manager: "java:maven"
    directory: "/modules/commons"
    update_schedule: "daily"
  - package_manager: "java:maven"
    directory: "/modules/document-generator"
    update_schedule: "daily"

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "production"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - ":robot: bot"
