apiVersion: skaffold/v1
kind: Config
profiles:
  - name: local
    build:
      artifacts:
        - image: registry.hub.docker.com/alexanderr/ws-documents
          context: .
          jib:
            project:
            args:
              - -Denv.DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
              - -Denv.DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
              - -s../../settings.xml
              - -Pmodule_java,test-jar,xsd
              - -DskipTests
      local:
        push: true
        useDockerCLI: true
    deploy:
      helm:
        releases:
          - name: documents
            chartPath: document-charts
            namespace: my-project
            wait: true
            valuesFiles:
              - document-charts/values-default.yaml
              - document-charts/values-local.yaml
            values:
              image.repository: registry.hub.docker.com/alexanderr/ws-documents

  - name: do
    build:
      artifacts:
        - image: balchu/documents
          context: .
          jib:
            project:
            args:
              - -Denv.DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
              - -Denv.DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}
              - -s../../settings.xml
              - -Pmodule_java,test-jar,xsd
              - -DskipTests
      local:
        push: true
        useDockerCLI: true
    deploy:
      helm:
        releases:
          - name: documents
            chartPath: document-charts
            namespace: my-project
            wait: true
            valuesFiles:
              - document-charts/values-default.yaml
              - document-charts/values-do.yaml
            values:
              image.repository: balchu/documents

  - name: documents-db-local
    deploy:
      helm:
        releases:
          - name: documents-db
            chartPath: documents-db-charts
            namespace: my-project
            wait: true
            valuesFiles:
              - documents-db-charts/values-default.yaml
              - documents-db-charts/values-local.yaml

  - name: documents-db-do
    deploy:
      helm:
        releases:
          - name: documents-db
            chartPath: documents-db-charts
            namespace: my-project
            wait: true
            valuesFiles:
              - documents-db-charts/values-default.yaml
              - documents-db-charts/values-do.yaml
