name: Check for broken links

on: [push, pull_request]

jobs:
  broken-link-check:
    runs-on: ubuntu-latest
    name: Check for broken links in README.md
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install -g markdown-link-check
      - run: find . -name \*.md -exec markdown-link-check -c .broken-link-config.json {} \;
