name: Document-Generator-Web-Service

on: [ push, pull_request ]

jobs:
  non_module_java:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java: [ '8' ]
        architecture: [ 'x64', 'x86' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        timeout-minutes: 20
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"non_module_java","test-jar","xsd"
  module_java:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java: [ '11', '12', '13', '14', '15-ea', '16-ea' ]
        architecture: [ 'x64', 'x86' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        timeout-minutes: 20
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"module_java","test-jar","xsd"
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"non_module_java","test-jar","xsd"
  module_zing_java:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java: [ '11', '12', '13', '14', '15-ea', '16-ea' ]
        architecture: [ 'x64', 'x86' ]
        os: [ ubuntu-latest ]
    name: Build with Zing JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 2
      - name: Setup JDK ${{ matrix.java }}
        uses: zing-actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        timeout-minutes: 20
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"module_java","test-jar","xsd"
