name: Build against JDKs
on: [push]

jobs:
  java_8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        run: mvn -Dfile.encoding=UTF-8 --lax-checksums -DskipTests=true clean package -Ptest-jar,xsd
  java_11:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        architecture: [ 'x64' ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        run: mvn -Dfile.encoding=UTF-8 --lax-checksums -DskipTests=true clean package -Pjava11,test-jar,xsd
