name: Document-Generator-Web-Service

on: [push]

jobs:
  non_module_java:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        java: [ '8' ]
        architecture: [ 'x64', 'arm' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        timeout-minutes: 20
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"non_module_java","test-jar","xsd"
  module_java:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        java: [ '11', '12', '13' ]
        architecture: [ 'x64', 'arm' ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jdk
          architecture: ${{ matrix.architecture }}
      - name: Build with Maven
        timeout-minutes: 20
        run: mvn clean package --lax-checksums -D"file.encoding"=UTF-8 -DskipTests=true -DprofileIdEnabled=true -P"module_java","test-jar","xsd"
