name: Daily build

on:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  macos-build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: "recursive"
          fetch-depth: 2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8

      - name: Build with Maven
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 20
        run: mvn clean package --errors --batch-mode --lax-checksums -DskipTests=true -P"non_module_java","test-jar","xsd","dev"
  windows-build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: "recursive"
          fetch-depth: 2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 1.8

      - name: Build with Maven
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 20
        run: mvn clean package --errors --batch-mode --lax-checksums -DskipTests=true -P"non_module_java","test-jar","xsd","dev"
