name: Document-Generator-Web-Service-health-check

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-18.04
    steps:
      - name: curl actuator
        id: ping
        run: |
          echo "::set-output name=status::$(curl ${{secrets.SERVER_HOST}}/api/actuator/health)"
      - name: health check
        run: |
          if [[ "${{ steps.ping.outputs.status }}" != *"UP"* ]]; then
            echo "health check is failed"
            exit 1
          fi
          echo "It's OK"
      - name: send alert in telegram
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Health check of the:
            ${{secrets.SERVER_HOST}}/api/actuator/health
            failed with the result:
            ${{ steps.ping.outputs.status }}