name: Labeler

on:
  - pull_request

jobs:
  assign:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/labels.yaml"
