name: Verifier

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  triage:
    runs-on: ubuntu-18.04
    steps:
      - uses: zwaldowski/match-label-action@v4
        with:
          allowed: 'type:fix, type:features, type:documentation, type:tests, type:config'
