name: Release2

on:
  milestone:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up JDK'
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Prepare git
      run: git config --global core.autocrlf false

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 'Attach git to origin with write access'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout master
        git remote rm origin
        git remote add origin "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

    - name: 'Stash current version to environment variable'
      run: echo ::set-env name=BACH_VERSION::$(java src/bach/Version.java)

    - name: 'Set version to ${{ github.event.milestone.title }}'
      run: java src/bach/Version.java ${{ github.event.milestone.title }}

    - name: 'Build using Bootstrap.java'
      run: java src/bach/Bootstrap.java

    - name: 'Commit all changed files, tag, and push origin'
      run: |
        git commit --all --message "Release ${{ github.event.milestone.title }}"
        git tag ${{ github.event.milestone.title }}
        git push origin master --tags

    - name: 'Create release'
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.milestone.title }}
        release_name: Release ${{ github.event.milestone.title }}
        draft: false
        prerelease: false

    - name: 'Deploy (bintray)'
      env:
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
      run: |
        mkdir --parents ~/.m2
        echo "<settings><servers><server><id>bintray-sormuras-maven</id><username>sormuras</username><password>${BINTRAY_KEY}</password></server></servers></settings>" > ~/.m2/settings.xml
        source .bach/out/maven-deploy-bintray-sormuras-maven.sh

    - name: 'Restore previous version from environment variable'
      run: |
        java src/bach/Version.java ${BACH_VERSION}
        git commit --all --message "Back to development of version ${BACH_VERSION}"
        git push origin master
